name: Publish PDF

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install TeX Live package
        run: sudo apt-get install -y texlive
      
      - name: Compile LaTeX document
        run: make build
          
      - name: Upload PDF document
        uses: actions/upload-artifact@v2
        with:
          name: diplomski_rad
          path: diplomski_rad.pdf
