name: Publish PDF

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: diplomski_rad.tex
          
      - name: Upload PDF document
        uses: actions/upload-artifact@v2
        with:
          name: diplomski_rad
          path: diplomski_rad.pdf
